### ISSUE TITLE
Show item recipe result in crafting menu

### ISSUE THREAD

**Issue by Drigonis** [TheDeathlyCow/tdc-data#2]
When you're crafting a custom item from a datapack, it usually just shows as a knowledge book or whatever they decide to make it craft. I think it would be cool (if possible at least) that it guesses and shows the actual item with all the NBT data in the crafting output, rather than the knowledge book or such.

**Comment by TheDeathlyCow** [comment]
Interesting idea, I can see a lot of use for something like that. Unfortunately it would be pretty hard to guess exactly which item is being given. That is something that is very implementation-specific. For example, how is the resulting item given? Is it using `/give`, `/loot`, `/item`, or something else entirely? It's hard to say. More importantly, this may result in overriding vanilla behaviours. That is a line that this mod should *never* cross. If you're a developer and going for the mod + datapack route, I think it would be better to just use a mod like [NBT crafting](https://www.curseforge.com/minecraft/mc-mods/nbt-crafting) and cut out the knowledge book middle man.
