### ISSUE TITLE
Version update

### ISSUE THREAD

**Issue by ThatBird20** [TheDeathlyCow/tdc-data#9]
Hi, im trying to find a modpack that has the /freeze command for newer versions, do you have any plans on updating this modpack to 1.21+ or know a mod that has this feature? thank you

**Comment by TheDeathlyCow** [comment]
I dont really plan to update it right now unfortunately. the closest I have available is [Thermoo](https://github.com/TheDeathlyCow/thermoo) which has a similarish temperature command, but is not quite the same.

**Comment by ThatBird20** [comment]
Thank you!

**Comment by TheDeathlyCow** [comment]
Made an issue in TheDeathlyCow/thermoo#36 to add this command. Thermoo should be able to work server side and shouldn't have any gameplay effects, so you can use it standalone for that if you need.
